### ISSUE TITLE
Support for Mermaid Graphs in documentation

### ISSUE THREAD

**Issue by tedivm** [pypi/warehouse#13083] opened 2023-02-25 17:09 UTC
**What's the problem this feature will solve?**

[Mermaid](https://mermaid.js.org/#/) is a diagramming system that allows diagrams to be defined in Markdown. It uses javascript to convert the text into an SVG. It is supported by Github, so any markdown on Github also supports mermaid.

**Describe the solution you'd like**

The [QuasiQueue](https://pypi.org/project/quasiqueue/) project uses Mermaid. The PyPi project just displays it as a codeblock, rather than a graph. It does render [on Github](https://github.com/tedivm/quasiqueue/). It would be nice if PyPi supported it since it would mean diagrams could be easily embedded in documentation.

**Additional context**

* [Integration Documentation](https://mermaid.js.org/intro/n00b-gettingStarted.html)
* [Existing Integrations](https://mermaid.js.org/ecosystem/integrations.html)

**Comment by di** [comment] 2023-02-25 17:45
Duplicate of https://github.com/pypa/readme_renderer/issues/223.

**Closed by di** 2023-02-25 17:45 UTC
Labels: feature request, requires triaging
