### ISSUE TITLE
Pypi is not picking up required torch 2.0.1 dependencies correctly, this breaks install via poetry

### ISSUE THREAD

**Issue by atalman** [pypi/warehouse#14000] opened 2023-06-22 19:57 UTC
**Describe the bug**

[Torch 2.0.1 ](https://pypi.org/project/torch/#files) packages

torch-2.0.1-cp311-cp311-manylinux1_x86_64.whl 
torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl 
torch-2.0.1-cp39-cp39-manylinux1_x86_64.whl 
torch-2.0.1-cp38-cp38-manylinux1_x86_64.whl 

Have following dependencies listed as part of METADATA file:
```
Requires-Dist: filelock
Requires-Dist: typing-extensions
Requires-Dist: sympy
Requires-Dist: networkx
Requires-Dist: jinja2
Requires-Dist: nvidia-cuda-nvrtc-cu11 (==11.7.99) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cuda-runtime-cu11 (==11.7.99) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cuda-cupti-cu11 (==11.7.101) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cudnn-cu11 (==8.5.0.96) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cublas-cu11 (==11.10.3.66) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cufft-cu11 (==10.9.0.58) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-curand-cu11 (==10.2.10.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cusolver-cu11 (==11.4.0.1) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cusparse-cu11 (==11.7.4.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-nccl-cu11 (==2.14.3) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-nvtx-cu11 (==11.7.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: triton (==2.0.0) ; platform_system == "Linux" and platform_machine == "x86_64"
Provides-Extra: opt-einsum
Requires-Dist: opt-einsum (>=3.3) ; extra == 'opt-einsum'
```

However this query return only part of the dependencies, none of the nvidia-cuda packages are returned:
```
curl -s https://pypi.org/pypi/torch/2.0.1/json | jq '.info.requires_dist'
[
  "filelock",
  "typing-extensions",
  "sympy",
  "networkx",
  "jinja2",
  "opt-einsum (>=3.3) ; extra == 'opt-einsum'"
]
```

This is causing the issue when installed via poetry:
https://github.com/python-poetry/poetry/issues/7902

**Expected behavior**
Return all required dependencies

**To Reproduce**
See above

**My Platform**
Linux

**Comment by di** [comment] 2023-06-22 20:13
Not all distributions for this release have the same dependencies. The first artifact uploaded for the release has what is provided in the JSON API: https://inspector.pypi.io/project/torch/2.0.1/packages/3c/67/7e19ebc15430f7385baee359383744c03d3600b51def9b399d0b8686e892/torch-2.0.1-cp39-none-macosx_11_0_arm64.whl/torch-2.0.1.dist-info/METADATA#line.31-37

The root cause of this is https://github.com/pypi/warehouse/issues/8090, since it doesn't really make sense to add _all_ dependencies across all files in a release either. 

Given that, I think this can probably be closed in favor of #8090.

**Comment by di** [comment] 2023-06-22 20:32
I'm not 100% on how Poetry works, but I think that would have the effect of these sub-dependencies getting included for _all_ PyTorch installs, not just the one that actually needs it. That might not be an issue, but only if the "file with most dependencies first" has a superset of all possible sub-dependencies.

Note that this is strictly a Poetry issue because they're using our non-standardized JSON API. If you switch to using `pip` this will work correctly.

**Comment by di** [comment] 2023-07-10 14:09
Closing as a duplicate of https://github.com/pypi/warehouse/issues/8090.

**Closed by di** 2023-07-10 14:09 UTC
Labels: requires triaging, bug :bug:
