### ISSUE TITLE
incorrect author email mapping

### ISSUE THREAD

**Issue by lucascolley** [pypi/warehouse#17033] opened 2024-11-05 11:42 UTC
**Describe the bug**
For the following in `pyproject.toml`:

```toml
authors = [
    { name = "Lucas Colley", email = "lucas.colley8@gmail.com" },
    { name = "Open Source Contributors" },
]
```

[PyPI displays](https://pypi.org/project/array-api-extra/):

> Author: [Open Source Contributors](mailto:lucas.colley8@gmail.com)

where the hyperlink is `mailto:lucas.colley8@gmail.com`.

**Expected behavior**

> Author: [Lucas Colley](mailto:lucas.colley8@gmail.com), Open Source Contributors

**To Reproduce**

**My Platform**

**Additional context**

**Comment by miketheman** [comment] 2024-11-05 11:56
Duplicate of https://github.com/pypi/warehouse/issues/14813

**Closed** 2024-11-05 11:56 UTC
Labels: requires triaging, bug :bug:
