### ISSUE TITLE
Provide an easy way to check modules exposed by the package through API

### ISSUE THREAD

**Issue by mknorps** [pypi/warehouse#12710] opened 2022-12-21 14:21 UTC
**What's the problem this feature will solve?**

There is no programmatic way to find out what modules a package exposes without downloading the package.
This feature is needed for the efficient translation of imports in Python code to the packages they may have come from.

For example `google-api-python-client` exposes `apiclient`, `googleapiclient` and `googleapiclient/discovery_cache`. Writing a Python program, you would have:
```
import apiclient
```
Just looking at the import does not give you any information from which library it was taken, unless it is installed already. 

**Describe the solution you'd like**

There are two ends to this stick:
1. Provide exposed modules via API for each package. Add a field that will contain content of `top_level.txt` file.
2. Allow for a search by import name (for example API that provides all packages exporting `apiclient`)

**Additional context**

Libraries for automatic generation of requirements.txt from Python source code deal with it in following ways:
1. [Pipreqs](https://github.com/bndr/pipreqs) has a static [mapping file](https://github.com/bndr/pipreqs/blob/master/pipreqs/mapping) from package name to imports names.
2. [Pigar](https://github.com/damnever/pigar) uses a combination of a database shipped with the package with downloading packages from PyPI, unpacking and [looking](https://github.com/damnever/pigar/blob/75c28815f7b6055fe6e6d401cb1b295274a2ed5b/pigar/unpack.py#L106) at the content of `top_level.txt` files.

**Comment by di** [comment] 2022-12-21 15:08
I think this is likely a duplicate of https://github.com/pypi/warehouse/issues/5375?

**Comment by mknorps** [comment] 2022-12-21 15:20
> I think this is likely a duplicate of #5375?

Partially - proposed solution number 2 is exactly issue #5375.
Solution 1 is I guess simpler to implement, though less useful in searching by import name. It adds a field to JSON API containing exposed modules. So at least there is no need to download the package from PyPI only to extract `top_level.txt` content.

So in a perfect world, I would like to have an API that I can search by import name and get a list of candidate packages. 
In a reasonably nice world, I would like to have information on import names for each PyPI package available easier (without downloading and unpacking) via API it would already help a lot.

**Comment by di** [comment] 2022-12-21 15:33
I think at the root, the 'hard' part of both of these feature requests is the same: PyPI would need a) some way to introspect the artifacts that are uploaded, b) some way to derive the imports from that c) and to store the results.

Given that I think we can merge this into #5375 if you want to add a comment there?

**Comment by mknorps** [comment] 2022-12-22 10:55
You can merge.
Can I help with solving this issue? 
What additional context should I need?
#5375 has been there for some time, does it mean it is a hard issue or a non-priority, or both?

**Comment by di** [comment] 2023-01-05 14:34
> Can I help with solving this issue?

Sure! A first step towards this would be prototyping how this would work in https://github.com/pypi/inspector first

 > https://github.com/pypi/warehouse/issues/5375 has been there for some time, does it mean it is a hard issue or a non-priority, or both?
 
 It's hard! Introspecting the artifacts requires unpacking/consuming untrusted code in production, we need a safe way to do this. https://github.com/pypi/inspector is a step towards this.
 
 I'll close this in favor of #5375.

**Comment by dstufft** [comment] 2023-05-23 04:44
Closing this, @di mentioned he was going to, then never did :)

**Closed by dstufft** 2023-05-23 04:44 UTC
Labels: feature request, requires triaging
