### ISSUE TITLE
Adding a "did you mean" link on the 404 page

### ISSUE THREAD

**Issue by tusharsadhwani** [pypi/warehouse#16292] opened 2024-07-17 18:18 UTC
**What's the problem this feature will solve?**

Two problems:

- When you typo a package, we can show a link to the pre-existing package that has a similar name.
- When choosing a package name, I check to ensure it doesn't already exist on PyPI. Right now, PyPI can show a 404 page but still reject the package name during upload. There is no clear indicator for which package name will be accepted and which will be rejected, until you try uploading it.

**Describe the solution you'd like**

Since `warehouse` already checks for similar names when trying to upload a new package, that same code can be used on the 404 page, and it can show a "did you mean?" link, to either the existing package, or to the standard library module with the same name.

Would a PR be welcome?

**Comment by di** [comment] 2024-08-06 22:07
Hi @tusharsadhwani, thanks for the feature request.

One issue with reusing the existing functionality is that there could be multiple matches (e.g. `some-project-name` might match `someprojectname` and `some-projectname`, etc) and there is no ordering between these, so there isn't quite one best "match", and there might be too many to make a "did you mean" message really meaningful.

Additionally, I think a more straightforward/obvious way to check the availability of a package name rather than relying on using search/404, like what's described in https://github.com/pypi/warehouse/issues/14535, would be a better user experience.

Given that, I'm going to close this as a duplicate of https://github.com/pypi/warehouse/issues/14535, but thanks for requesting this!

**Closed by di** 2024-08-06 22:07 UTC
Labels: feature request, requires triaging
