### ISSUE TITLE
Package owner not available in project JSON API

### ISSUE THREAD

**Issue by cristianmartinello-wf** [pypi/warehouse#13197] opened 2023-03-13 10:20 UTC
**What's the problem this feature will solve?**
Return the owner of the package in the [project JSON API ](https://warehouse.pypa.io/api-reference/json.html#get--pypi--project_name--json)

**Describe the solution you'd like**
Return the same information provided by the [`package_roles(package_name)` PyPI’s XML-RPC method](https://warehouse.pypa.io/api-reference/xml-rpc.html#package-roles-package-name)

**Comment by ewdurbin** [comment] 2023-03-13 10:33
I think this is a duplicate of #2914. Seems at the time (and I presume still) we're open to the idea, have just never had an implementation proposed.

**Closed by ewdurbin** 2023-03-13 10:33 UTC
Labels: feature request, requires triaging
