### ISSUE TITLE
Allow ssh authentication for uploads

### ISSUE THREAD

**Issue by jnahmias** [pypi/warehouse#5336] opened 2019-01-25 02:34 UTC
**What's the problem this feature will solve?**
Passwords are evil.  Everyone has too many of them.  For infrequent contributors, remembering yet another password so we can upload to PyPI is a pain.  This is especially noticeable since most git repos allow you to upload using an ssh key; so this is a break from the usual developer workflow.

**Describe the solution you'd like**
Rather than authenticating via username/password when uploading to PyPI, it would be great if an ssh public key could be used instead.  Similar to Github/Gitlab/etc, you would have a section on your user profile where you add your ssh public key.  Then twine would need to be able to upload via sftp or similar.

**Additional context**
Rumor has it that a previous incarnation of PyPI had this ability.  Please bring it back!

**Comment by ewdurbin** [comment] 2019-01-25 14:44
SSH uploads were supported before TLS was available for accessing PyPI.

We don't intend to reintroduce SSH for uploads, but rather to implement Tokens for accessing PyPI programatically.

Do the features suggested in #994 fulfill your concern? These are planned to be implemented this year as part of an RFP at https://github.com/python/request-for/blob/master/2019-Q1-PyPI/RFP.md

**Comment by brainwane** [comment] 2019-06-19 15:57
@jnahmias would it be okay to close this as a duplicate of #2315?

Also, to second Ernest, I think the features in #994 -- which we're working on this month -- should probably fulfill most of your needs here.

**Comment by merwok** [comment] 2019-06-19 16:03
They are different proposals:
- this one keeps the build step (on local computer or CI), just changes the upload mechanism from HTTPS (with password) to scp (with ssh key)
- #2315 is broader: PyPI would implement the git server protocol to allow devs to push a branch to PyPI, then have a build farm create the dists and register them

**Comment by dstufft** [comment] 2023-05-23 03:59
I'm going to close this. At this point I think it's very unlikely that we ever re-enable ssh based uploads, and we now have api tokens for upload.

**Closed by dstufft** 2023-05-23 03:59 UTC
Labels: feature request
