### ISSUE TITLE
[Search result order] Exact match is not the first card

### ISSUE THREAD

**Issue by roniemartinez** [pypi/warehouse#13597] opened 2023-05-07 00:34 UTC
**Describe the bug**
When searching in PyPI.org, the exact match is not the first search result.

Example: When searching `latex2mathml`, the first result is `mathml2latex` instead of `latex2mathml`

![image](https://user-images.githubusercontent.com/2573537/236651843-fb6815a2-217f-4ed4-ba9e-74032ea25594.png)

**Expected behavior**
Exact matches goes on top

**To Reproduce**
Search `latex2mathml`
See: https://pypi.org/search/?q=latex2mathml

**My Platform**

**Additional context**

**Comment by di** [comment] 2023-05-07 01:33
Duplicate of https://github.com/pypi/warehouse/issues/10718.

**Closed by di** 2023-05-07 01:33 UTC
Labels: requires triaging, bug :bug:
