### ISSUE TITLE
<s> in rendering of yaml and toml code blocks in long description.

### ISSUE THREAD

**Issue by cjw296** [pypi/warehouse#12310] opened 2022-10-04 07:39 UTC
**Describe the bug**

I have a [ReST README](https://github.com/cjw296/carthorse/blob/57e945dddb2e37fe887154083c40a3cdd6217f4c/README.rst) that is used for my project's long description, it contains:

```rest
.. code-block:: toml

    [tool.carthorse]
    version-from = "poetry"
    tag-format = "v{version}"
    when = [
      "version-not-tagged"
    ]
    actions = [
       { run="poetry publish --build"},
       { name="create-tag"},
    ]

```
...and:

```rest
.. code-block:: yaml

    carthorse:
      version-from: poetry
      tag-format: v{version}
      when:
        - version-not-tagged
      actions:
        - run: "poetry publish --build"
        - create-tag
```

This is rendered with a bunch of `<s>` tags in it on pypi.org.

**Expected behavior**

Should be rendered as it is on github: languages formatted (nice to have) but not with additional `<s>` in it. 

**To Reproduce**

Publish a package containing the above ReST in its long description and view it through the web interface.

For example:

```
[tool.carthorse]
version-from = "poetry"
tag-format = "v{version}"
when = [
  "version-not-tagged"
]
actions = [
   { run="poetry publish --build"},
   { name="create-tag"},
]
```

...is rendered as follows on pypi.org:

```
[tool.carthorse]
version-from = <s>"poetry"</s>
tag-format = <s>"v{version}"</s>
when = [
  <s>"version-not-tagged"</s>
]
actions = [
   { run=<s>"poetry publish --build"</s>},
   { name=<s>"create-tag"</s>},
]
```

**Comment by di** [comment] 2022-10-04 17:05
Closing as a duplicate of https://github.com/pypa/readme_renderer/issues/261.

**Closed by di** 2022-10-04 17:05 UTC
Labels: requires triaging, bug :bug:

**Comment by cjw296** [comment] 2022-10-04 17:47
@miketheman - I see https://github.com/pypi/warehouse/pull/12268 has been merged but https://pypi.org/project/carthorse/ is still not rendered correctly. Is there a release or deployment I should keep an eye out for?

**Comment by miketheman** [comment] 2022-10-04 17:50
There's a time delay from when the code is merged and a background process rerenders the content, so it can take ~14 days to get through the entire backlog.

**Comment by cjw296** [comment] 2022-10-04 17:50
Perfect, thanks!
