### ISSUE TITLE
Promote include name in search

### ISSUE THREAD

**Issue by s7726** [pypi/warehouse#13851] opened 2023-06-03 15:49 UTC
**What's the problem this feature will solve?**

Currently when a user searches for a particular package, often by the name seen in an `include package` or `from package include class` line, the most relevant result is rather often not the top result, leading to potentially incorrect or malicious packages coming up first.

**Describe the solution you'd like**

I'd like to see the common include name, if it matches the search term, promoted in the results.

**Additional context**

Go to pypi
Search for pil, or PIL
The actual Pillow package isn't even in the first page of results.

Search for pandas
The top result is "pandas2" whatever that is.

There are likely other criteria that might be useful to promote e.g. downloads, GitHub stars, etc.

**Comment by miketheman** [comment] 2023-06-03 15:52
Duplicate of #10718.

**Comment by miketheman** [comment] 2023-06-03 15:53
Duplicate of #5375

**Closed by miketheman** 2023-06-03 15:52 UTC
Labels: feature request, search
