### ISSUE TITLE
Packages randomly missing from simple index

### ISSUE THREAD

**Issue by nateprewitt** [pypi/warehouse#10390] opened 2021-11-19 17:31 UTC
**Describe the bug**
We upload the AWS Python packages ([awscli](https://pypi.org/project/awscli/), [boto3](https://pypi.org/project/boto3/), and [botocore](https://pypi.org/project/botocore/)) each weekday with changes to keep the tools up-to-date with the company's services. We realize that generates a significant number of entries in the PyPI index, so we're an outlier to most projects.

Recently, we've started noticing that periodically (every 2-3 weeks) one or more of the uploads will being missing from either the `/project` page or the `/simple` index, but never both. We're confident the uploads are succeeding from our twine logs and the fact it's always upload in at least one of those two pages. `/project` isn't a major issue, but when the `/simple` entry is missing, users are receiving errors in pip preventing them from installing the day's updates.

I don't have a strong understanding of the sync mechanism, but it seems whatever job is populating these in PyPI may be dying or halting. Whenever these issues arise, we've been waiting for the next day's release which seems to fix all entries immediately. The goal of this ticket is to get some more insight into what's happening and if there are actions we can take to mitigate it.

**Expected behavior**
Packages to be available in the `/simple/<project>` index within a reasonable amount of time after upload.

**To Reproduce**
https://pypi.org/simple/boto3/ is currently missing entries for 1.20.9. This will likely be remedied with our next release at ~1200 PT but is currently causing issues for users installing with `pip`.

**My Platform**
Our build and uploads are using:
```
setuptools==57.5.0
wheel==0.37.0
twine==1.15.0
```

**Comment by di** [comment] 2021-11-19 17:41
It seems like the cache purge may be occasionally failing after the new version is published. I did a `curl -xpurge https://pypi.org/simple/boto3/` and the page now includes `1.20.9`.

**Comment by nateprewitt** [comment] 2021-11-19 17:47
Great, I just saw the update, thanks! Is this something we'd have any control over externally or does it require an API token to invoke a purge on the cache? Not sure what the best path is going forward.

**Comment by di** [comment] 2021-11-19 17:53
Anyone can purge the cache with that command, so in the short term, you could use that to avoid the issue when you encounter it. But long-term we need to figure out why this is happening.

**Comment by nateprewitt** [comment] 2021-11-19 18:00
Ok, we'll keep a note of that for the next time it happens. I think that answers our questions, so I'm fine closing this unless you want it to track anything. Thanks again!

**Comment by di** [comment] 2021-11-19 18:01
Let's definitely leave it open to track this, it shouldn't be happening.

**Comment by di** [comment] 2021-11-19 18:23
I charted our purge count per day over time according to Fastly, looks like there are some days when we've issued significantly less purges than expected, including in the last 24 hours:

![chart](https://user-images.githubusercontent.com/294415/142672364-3a471f45-bd7f-4cc3-b54b-722503402da9.png)

(I've highlighted periods that correspond to higher "weekday" traffic here)

**Comment by nateprewitt** [comment] 2021-11-19 19:39
I've gone back through our tickets to catalog incident dates within that graph's timeline. I'm not sure if there's a clear correlation but there are dips around the event dates.

**2021-10-12:** boto/botocore#2530 (botocore simple index)
**2021-10-19:** boto/boto3#3047 (boto3 simple index)
**2021-11-08:** boto/boto3#3066 (boto3 simple index)
**2021-11-18:** boto/boto3#3075 (boto3 simple index)

**Comment by cooperlees** [comment] 2022-05-02 16:55
Could this be similar to the long standing JSON stale cached responses too maybe? https://github.com/pypa/warehouse/issues/4892

**Comment by aptalca** [comment] 2022-06-10 01:01
It seems like this issue just hit pikepdf 5.1.4 earlier today where the sdist appears in files: https://pypi.org/project/pikepdf/#files
but not in simple index https://pypi.org/simple/pikepdf/

**Comment by di** [comment] 2022-06-26 22:26
Seems like we are experiencing this again today. One thought I had here was whether two or more purges in quick succession might be causing the more recent purges to be ignored, which might be the case with uploads.

**Comment by mvaled** [comment] 2022-06-27 06:31
I'm suffering something similar.  I've just pushed (several times) the version 1.0.0b14 of this package https://pypi.org/project/xotl.plato/ but it remains with older version 1.0.0b13; [the `/simple` page](https://pypi.org/simple/xotl-plato/) also misses the last version of the package.  However, there's a page for that version: https://pypi.org/project/xotl.plato/1.0.0b14/

**Comment by KotlinIsland** [comment] 2022-06-27 07:05
I pushed a pre-prelease to [basedmypy](https://pypi.org/project/basedmypy/1.4.0rc1/#history) 7 hours ago and am yet to see any movement on /simple

**Comment by mvaled** [comment] 2022-06-27 07:30
For me, sending 'purge' worked:

```
$ curl -X purge 'https://pypi.org/simple/xotl.plato'
301 Moved Permanently

The resource has been moved to /simple/xotl.plato/; you should be redirected automatically.
```

**Comment by mauritsvanrees** [comment] 2022-06-27 12:17
> For me, sending 'purge' worked:
> 
> ```
> $ curl -X purge 'https://pypi.org/simple/xotl.plato'
> 301 Moved Permanently
> 
> The resource has been moved to /simple/xotl.plato/; you should be redirected automatically.
> ```

It would seem that this does nothing: you get redirected to the same url with a slash at the end.
Maybe the purge somehow worked for you, but it does not work for me. I have the same problem with `plone.staticresources`, and I am not allowed to do a purge:

```
$ bin/pip install --no-deps --pre plone.staticresources==2.0.0b3
ERROR: Could not find a version that satisfies the requirement plone.staticresources==2.0.0b3 (from versions: 1.0a1, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 2.0.0a1, 2.0.0a2, 2.0.0a3, 2.0.0b1)
ERROR: No matching distribution found for plone.staticresources==2.0.0b3

$ curl -X purge https://pypi.org/simple/plone-staticresources
301 Moved Permanently

The resource has been moved to /simple/plone-staticresources/; you should be redirected automatically.
$ curl -X purge https://pypi.org/simple/plone-staticresources/
405 Method Not Allowed

The method PURGE is not allowed for this resource. 
```

It actually would surprise me if a purge worked as anonymous user.

**Comment by KotlinIsland** [comment] 2022-06-27 12:19
Worked for me 😁

**Comment by mauritsvanrees** [comment] 2022-06-27 12:33
Aha, someone told me it must be `PURGE` with all capital letters:

    $ curl -X PURGE https://pypi.org/simple/plone-staticresources/

Might depend on your system, or maybe the version of curl. Now it works for me. :-)

Would be good to have the underlying problem fixed of course, but for now I am happy to have a workaround.

**Comment by jvansanten** [comment] 2022-06-27 13:04
Seems like this was happening a lot today; I ran into this and was tearing my hair out trying to figure out how pip was getting a different index than I dumped with `curl` before running across this thread. PURGE also worked for me:

```bash
> curl -s https://pypi.org/simple/ampel-core/ | grep SERIAL                                            
<!--SERIAL 14258990-->
> curl -sH 'Accept-Encoding: gzip, deflate' https://pypi.org/simple/ampel-core/ | gunzip - | grep SERIAL
<!--SERIAL 14226377-->
> curl -XPURGE https://pypi.org/simple/ampel-core/ 
{ "status": "ok", "id": "4055-1656078210-1944818" }%                                                                                                                        
> curl -sH 'Accept-Encoding: gzip, deflate' https://pypi.org/simple/ampel-core/ | gunzip - | grep SERIAL
<!--SERIAL 14258990-->
```

**Comment by fengwei-tian** [comment] 2022-12-01 22:18
> It seems like the cache purge may be occasionally failing after the new version is published. I did a `curl -xpurge https://pypi.org/simple/boto3/` and the page now includes `1.20.9`.

I tried the same approach and got `{"msg":"Provided credentials are missing or invalid"}`

**Comment by di** [comment] 2022-12-01 22:40
Purging is no longer publicly available. Sorry.

**Comment by fengwei-tian** [comment] 2022-12-01 22:49
> Purging is no longer publicly available. Sorry.

We have the same issue again, could you please help us to do another XPURGE for boto3? Thanks!

**Comment by fengwei-tian** [comment] 2022-12-01 22:49
https://pypi.org/project/boto3/ we have a new release 3 hours ago.

**Comment by itsmonktastic** [comment] 2022-12-01 23:12
I think the same is needed for botocore https://pypi.org/simple/botocore/ which is missing 1.29.21 released today 🙏 ( correctly listed on https://pypi.org/pypi/botocore/json )

**Comment by di** [comment] 2022-12-07 17:40
@nateprewitt IIRC you did some analysis of the inconsistencies between different Fastly POPs when this happens, but I can't find it in this thread or elsewhere. Am I remembering correctly? Could you share that again if so?

**Comment by di** [comment] 2022-12-09 14:23
(Sorry, I was thinking of this: https://github.com/pypi/warehouse/issues/12214#issuecomment-1277869584)

**Comment by di** [comment] 2022-12-12 19:51
I'm closing this in favor of https://github.com/pypi/warehouse/issues/12214 which is technically a duplicate of this issue, but has a bit more detail/discussion. Please watch/comment on that issue instead, thanks!

**Closed by di** 2022-12-12 19:51 UTC
Labels: bug :bug:
