### ISSUE TITLE
UI/Web-Frontend: Python versions sorted alphabetically instead of chronologically

### ISSUE THREAD

**Issue by riggedCoinflip** [pypi/warehouse#12361] opened 2022-10-14 20:15 UTC
**Describe the bug**

The list on the left navbar of projects is sorted alphabetically by python version instead of chronologically. This means we currently have orders like this (taken from dotenv project):

- Python
- Python 3
- Python 3.10
- Python 3.11
- Python 3.7
- Python 3.8
- Python 3.9
- Python Implementation PyPy

which is hard to read.

![Capture](https://user-images.githubusercontent.com/59298775/195934506-1adb5f08-fedc-40a8-ae2d-f186fb1020a6.PNG)

**Expected behavior**

Sorted chronologically where applicable

**To Reproduce**

Open any project on pypy website, for example:
https://pypi.org/project/numpy/
https://pypi.org/project/pandas/
https://pypi.org/project/python-dotenv/

Scroll down untill you see the "Programming language" section in the navbar.

**My Platform**

Irrelevant for problem (Windows Chrome 106)

**Additional context**

**Comment by di** [comment] 2022-10-14 20:38
Duplicate of https://github.com/pypi/warehouse/issues/8843.

**Closed by di** 2022-10-14 20:38 UTC
Labels: requires triaging, bug :bug:
