### ISSUE TITLE
Negative range HTTP requests returning 501

### ISSUE THREAD

**Issue by domdfcoding** [pypi/warehouse#13201] opened 2023-03-13 15:02 UTC
**Describe the bug**
Until recently (certainly at least September 2022) it was possible to make HTTP requests to files.pythonhosted.org with the `Range` header set to e.g. `bytes=-100` to get the last 100 bytes of the file. As of March 2023 an error 501 is returned with the message "Unsupported client range".

**Expected behavior**
The last 100 etc. bytes of the file are returned.

**To Reproduce**
* Failing example (last 100 bytes): `curl -v -H Range:bytes=-100 https://files.pythonhosted.org/packages/94/e2/0a5630e43ca0b21ca891ec3a697bdb98a25663e27ebd1079ab55e8c68e72/domdf_python_tools-2.9.1-py3-none-any.whl`
* Working example (first 100 bytes):  `curl -v -H Range:bytes=0-100 https://files.pythonhosted.org/packages/94/e2/0a5630e43ca0b21ca891ec3a697bdb98a25663e27ebd1079ab55e8c68e72/domdf_python_tools-2.9.1-py3-none-any.whl`

**My Platform**
Can reproduce on multiple computers and ISPs in the north and south of England. The connections are to both Fastly's LON and LCY data centres. 

**Additional context**

Requests with a start and end byte (e.g. bytes=100-200) work fine.

**Comment by miketheman** [comment] 2023-03-13 15:04
Duplicate of #12823

**Closed** 2023-03-13 18:06 UTC
Labels: requires triaging, bug :bug:
