### ISSUE TITLE
File size limit increase for vLLM

### ISSUE THREAD

**Issue by pcmoritz** [pypi/warehouse#15922] opened 2024-05-07 22:27 UTC
Dear all,

we are developing a library for high throughput LLM serving (https://github.com/vllm-project/vllm) and we are running into the 100MB limit. Could you increase it to 200MB for us? Unfortunately the wheel size needs to be a little larger than usual since the wheels include a bunch of GPU code and kernels which need to be compiled for different architectures.

- Project name: vLLM (https://pypi.org/project/vllm/)
- Size of current release: 100MB
- Indexes: both test PyPI and PyPI

Thanks a lot for your help!

cc @WoosukKwon @zhuohan123 @simon-mo

**Comment by simon-mo** [comment] 2024-05-08 00:44
🙏 We also have a support ticket opened here: https://github.com/pypi/support/issues/3792

**Comment by di** [comment] 2024-05-08 06:59
Closing as a duplicate of https://github.com/pypi/support/issues/3792.

Please don't intentionally create duplicate issues.

**Closed by di** 2024-05-08 06:59 UTC
