### ISSUE TITLE
Provide daily dumps of the pypi index

### ISSUE THREAD

**Issue by bitplane** [pypi/warehouse#12242] opened 2022-09-21 01:28 UTC
**What's the problem this feature will solve?**

`pip search` is broken in the default use-case because the XMLRPC service is down.

Providing a nightly dump would mean it'd be easy to fix - just download the list and search it locally. If it was just a file somewhere then you could redirect to a mirror that has it, I'm sure many organizations with lots of bandwidth would happily mirror it to keep pypi's search working. Plus it'd be a useful file in general.

**Describe the solution you'd like**
Dump the packages, versions, description and a list of downloads to a file. Dump it somewhere and let it the `pip search` problem fix itself.

**Additional context**
A useful alternative to `pip search` out of the box, `pip-search`, scrapes the website at the moment. The next time someone makes an abusive bot that hammers that endpoint, then I assume you'll have the search problem all over again.

**Comment by di** [comment] 2022-09-21 15:05
Duplicate of #8802.

**Closed by di** 2022-09-21 15:05 UTC
Labels: feature request, requires triaging
