### ISSUE TITLE
incosistent release data for new releases

### ISSUE THREAD

**Issue by chargr** [pypi/warehouse#12655] opened 2022-12-09 02:57 UTC
**Describe the bug**
Inconsistent behavior when download (source) files on new releases.

**Expected behavior**
All files exist consistency after a publisher has completed pushing files.

**To Reproduce**
Accessed this package shortly after release.

Repeated from a second computer (and different external IP but same netblock)
There the python script worked, pip failed, curl worked.

this computer
python script failed, pip failed, curl works
output below:

```
    url = f"https://pypi.org/pypi/{module}/json"
    r = requests.get(url)
```

```
$ pip --isolated download --no-binary :all: rapidfuzz==2.13.4
ERROR: Could not find a version that satisfies the requirement rapidfuzz==2.13.4 (from versions: 0.0.6, 0.0.7, 0.0.8, 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.7.0, 0.7.1, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.11, 0.7.12, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.9.0, 1.9.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.0.15, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.3.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.8.0, 2.9.0, 2.10.0, 2.10.1, 2.10.2, 2.10.3, 2.11.0, 2.11.1, 2.12.0, 2.13.0, 2.13.1, 2.13.2, 2.13.3)
ERROR: No matching distribution found for rapidfuzz==2.13.4
```

```
$ curl https://pypi.org/pypi/rapidfuzz/json | jq '.releases["2.13.4"][-1]'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4261k  100 4261k    0     0  26.5M      0 --:--:-- --:--:-- --:--:-- 26.5M
{
  "comment_text": "",
  "digests": {
    "md5": "478f2769e54d0ee41ab71bae90034fa7",
    "sha256": "85f5e8667b8e6cb7687c86374c60b133abdc76b2af24455172388c5d7ab2787b"
  },
  "downloads": -1,
  "filename": "rapidfuzz-2.13.4.tar.gz",
  "has_sig": false,
  "md5_digest": "478f2769e54d0ee41ab71bae90034fa7",
  "packagetype": "sdist",
  "python_version": "source",
  "requires_python": ">=3.7",
  "size": 843410,
  "upload_time": "2022-12-08T22:07:39",
  "upload_time_iso_8601": "2022-12-08T22:07:39.011305Z",
  "url": "https://files.pythonhosted.org/packages/87/d4/4fcd1d0f6b702969f2d1f1068d2bc618f2a1e859c8f4881f523687b855bd/rapidfuzz-2.13.4.tar.gz",
  "yanked": false,
  "yanked_reason": null
}
```

**My Platform**
```
$ dig +short pypi.org
151.101.64.223
151.101.128.223
151.101.0.223
151.101.192.223
```

**Comment by di** [comment] 2022-12-09 14:21
Duplicate of https://github.com/pypi/warehouse/issues/12214.

**Closed by di** 2022-12-09 14:21 UTC
Labels: requires triaging, bug :bug:
