### ISSUE TITLE
Report broken packages/conflicts/dead_links

### ISSUE THREAD

**Issue by andrew-azarov** [pypi/warehouse#14036] opened 2023-06-28 10:45 UTC
**What's the problem this feature will solve?**

While  we heavily rely on the goodwill of the publisher/maintainer, there's still some things which can be reported by verified users and/or community.  This can help in dire situations, data corruption incidents or major conflicts.

**Describe the solution you'd like**
Sort of like 'wikipedia' system a discussion must be formed per each package and ability to report old or broken packages and possible conflicts or security incidents would be great with display on the main page of the package.
Like huge warning "Doesn't work with python >=3.9", "Official Repository unavailable", "Doesn't work with sqlalchemy >= 2.0" or "Maintainer unresponsive". Many other package management software systems provide EOL reminders and warnings of these kinds which are handled by the community or verified maintainers of such systems.
During installation of packages through pip it can check for reported conflicts and abort unless forced to.

**Additional context**
Found out one of the important software we use to report taxes stopped doing its job because sqlalchemy upgraded during software update on the system. This caused a package which was marked as ok for ANY version of sqlalchemy to fail (actually it was ok only for major release 1, thank god no corruption of data happened).
Turns out package is abandoned, the official repository listed in pypi is 404, maintainer unavailable.
As the error was traced to sqlite package and not sqlalchemy it took some time to figure out the culprit and rollback sqlalchemy.

**Comment by di** [comment] 2023-06-28 12:16
Thanks for the issue. I think this is a duplicate of https://github.com/pypi/warehouse/issues/3896.

**Comment by di** [comment] 2023-07-10 14:09
Closing as a duplicate of https://github.com/pypi/warehouse/issues/3896.

**Closed by di** 2023-07-10 14:09 UTC
Labels: feature request, requires triaging
