### ISSUE TITLE
Use SPDX license names as classifiers

### ISSUE THREAD

**Issue by ralf-vogel** [pypi/warehouse#15901] opened 2024-05-03 13:59 UTC
## What's the problem this feature will solve?

For the license clearing of a product, it is vital to know the exact license a package is using.
Currently the packages can define classifiers like:
```
License :: OSI Approved :: MIT License
License :: OSI Approved :: BSD License
```
or just:
```
License :: OSI Approved
```

This is very unspecific and raises some important questions.
What `BSD License` does this refer to?
[SPDX](https://spdx.org/licenses/) lists 32 different BSD licenses.
Or even worse: what `OSI Approved` license is this package using?
There is a huge difference between the [MIT License](https://spdx.org/licenses/MIT.html) and the [GNU General Public License v2.0 or later](https://spdx.org/licenses/GPL-2.0-or-later.html) (especially regarding the copyleft).

So the classifiers might look useful, but in many cases they are not.

## The solution I would like
Instead of the unprecise classifiers above, the the packages should be labelled with unique license identifiers matching the **full names** in the [SPDX License List](https://spdx.org/licenses/).
This also means, that the group `License :: OSI Approved` should not be a valid classifier.

**Comment by di** [comment] 2024-05-03 22:48
Duplicate of https://github.com/pypa/trove-classifiers/issues/17.

**Closed by di** 2024-05-03 22:48 UTC
Labels: feature request, requires triaging

**Comment by ralf-vogel** [comment] 2024-05-06 18:51
FYI: the actual discussion about this topic has moved here:
https://discuss.python.org/t/pep-639-round-2-improving-license-clarity-with-better-package-metadata/12622
