### ISSUE TITLE
Getting "403 Invalid API Token: caveat must be an array" error

### ISSUE THREAD

**Issue by HubTou** [pypi/warehouse#15587] opened 2024-03-13 22:16 UTC
**Describe the bug**
Since today, while updating one of my PyPI packages with Twine, I'm getting a "403 Invalid API Token: caveat must be an array" error.
Last time it worked was 3 days ago.
I settled 2FA today (after the issue occurred) and even generated a new API key, but without better results.

**Expected behavior**
Successful upload of a new package version.

**To Reproduce**
$ python -m twine upload dist/*

**My Platform**
Operating System: freebsd-14.0-RELEASE-amd64
Python version: major=3, minor=9, micro=18, releaselevel='final', serial=0
Python packages:
keyring                       24.3.1
twine                         5.0.0

**Additional context**
Full verbose trace:
```
$ python -m twine upload dist/* --verbose
Uploading distributions to https://upload.pypi.org/legacy/
INFO     dist/pnu_libpnu-1.3.0-py3-none-any.whl (7.8 KB)
INFO     dist/pnu-libpnu-1.3.0.tar.gz (9.0 KB)
INFO     Querying keyring for password
WARNING  Error getting password from keyring
         Traceback (most recent call last):
           File "/usr/local/lib/python3.9/site-packages/twine/auth.py", line 81, in get_password_from_keyring
             return cast(str, keyring.get_password(system, username))
           File "/usr/local/lib/python3.9/site-packages/keyring/core.py", line 56, in get_password
             return get_keyring().get_password(service_name, username)
           File "/usr/local/lib/python3.9/site-packages/keyring/backends/fail.py", line 28, in get_password
             raise NoKeyringError(msg)
         keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you
         want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
Enter your API token:
INFO     username: __token__
INFO     password: <hidden>
Uploading pnu_libpnu-1.3.0-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 kB • 00:00 • 4.0 MB/s
INFO     Response from https://upload.pypi.org/legacy/:
         403 Invalid API Token: caveat must be an array
INFO     <html>
          <head>
           <title>403 Invalid API Token: caveat must be an array</title>
          </head>
          <body>
           <h1>403 Invalid API Token: caveat must be an array</h1>
           Access was denied to this resource.<br/><br/>
         Invalid API Token: caveat must be an array


          </body>
         </html>
ERROR    HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
         Invalid API Token: caveat must be an array
```

**Comment by di** [comment] 2024-03-13 22:25
Duplicate of #15586.

**Closed by di** 2024-03-13 22:25 UTC
Labels: requires triaging, bug :bug:
