### ISSUE TITLE
Search returns not-exact-match first

### ISSUE THREAD

**Issue by hazelnutfox** [pypi/warehouse#15264] opened 2024-01-24 13:28 UTC
**Describe the bug**

When searching for "tensorflow", search returns "tensorflow1" package first and real "tensorflow" second. 

**Expected behavior**

Tensorflow should appear first when searching for "tensorflow". 

In general: exact match for searched word should appear first as it's more intuitive. 

**To Reproduce**

[Link to search](https://pypi.org/search/?q=tensorflow&o=) / go to PyPI and enter "tensorflow" in search, then look at two top results and their order. 

**My Platform**

Unrelated to platform

**Additional context**

It's more of UX bug than "real" bug. But when someone enters exact name they know exists, they'd expect first result to be it (I clicked first result without thinking and only realised something is wrong when I noticed there's no wheels - I wanted to check wheel os+python combinations for tf).

Search algorithm would normally be hard to modify, but this is "exact match returned first" idea so I hope it's easier.

"tensorflow1" package is not related to real tf at all but it's not malicious (and it's not a placeholder that downloads tf)

**Comment by miketheman** [comment] 2024-01-24 14:26
Duplicate of #10718

**Closed by miketheman** 2024-01-24 14:26 UTC
Labels: requires triaging, bug :bug:
