### ISSUE TITLE
Cannot `pip install` recently released package from test.pypi after few hours from release

### ISSUE THREAD

**Issue by DanielRyszkaIBM** [pypi/warehouse#12272] opened 2022-09-26 15:36 UTC
**Describe the bug**
We've uploaded new version of `ibm-watson-machine-learning` package on test PyPI - version `1.0.247`
Twine upload seems to have worked correctly:
```
...
Uploading distributions to https://test.pypi.org/legacy/

Uploading ibm_watson_machine_learning-1.0.247-py3-none-any.whl

100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB • 00:00 • 56.1 MB/s

Uploading ibm_watson_machine_learning-1.0.247.tar.gz

100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.7/668.7 kB • 00:00 • 90.9 MB/s

View at:

https://test.pypi.org/project/ibm-watson-machine-learning/1.0.247/
```

But when we try to install this version of package, we are getting error:
```
% pip install -i https://test.pypi.org/simple/ ibm-watson-machine-learning==1.0.247 --no-cache-dir
Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement ibm-watson-machine-learning==1.0.247 (from versions: ...
...
ERROR: No matching distribution found for ibm-watson-machine-learning==1.0.247
```

I can see the package under link here: https://test.pypi.org/project/ibm-watson-machine-learning/1.0.247/
But I can't see it in simple API:
```
% curl -sH 'Accept-Encoding: gzip, deflate' https://test.pypi.org/simple/ibm-watson-machine-learning/ | gunzip - | grep "1.0.247"
(py310_x86) danielryszka@Daniels-MacBook-Pro ibm_watson_machine_learning % 
```
I can see previous version though in there:
```
% curl -sH 'Accept-Encoding: gzip, deflate' https://test.pypi.org/simple/ibm-watson-machine-learning/ | gunzip - | grep "1.0.246"
    <a href="https://test-files.pythonhosted.org/packages/ca/b5/3ac5187c171847f86bcf3e06aa9aaf54948a1412b58670fa39fbde8ea088/ibm_watson_machine_learning-1.0.246-py3-none-any.whl#sha256=2b1dd01214e9f0a34e64bf777cd708f95e454d86eaa9850de55f0df6f836cd72" data-requires-python="&gt;=3.7" >ibm_watson_machine_learning-1.0.246-py3-none-any.whl</a><br />
    <a href="https://test-files.pythonhosted.org/packages/56/f6/d581bea49db8a17fb05ec746b2bd5e2f64d12c2f65cd88b8eb632504203c/ibm_watson_machine_learning-1.0.246.tar.gz#sha256=27d01924da0ab76db278748f204be45f85fefd8e5edb2cdf8d234da4f9a49307" data-requires-python="&gt;=3.7" >ibm_watson_machine_learning-1.0.246.tar.gz</a><br />
```

The similar situation seems to have occured in the past with other packages based on previous issues in the repo, e.g.: https://github.com/pypi/warehouse/issues/11512

**Expected behavior**
New version of the package should be available to install.

**To Reproduce**
Try to install `ibm-watson-machine-learning-package` in version `1.0.247`.
E.g.:
```
pip install -i https://test.pypi.org/simple/ ibm-watson-machine-learning==1.0.247 
```

**My Platform**
I've tried it on two different platforms: Mac OS X (pip 21.2.4), RHEL

**Additional context**
N/A

**Comment by di** [comment] 2022-09-26 15:53
I manually purged this page from our CDN and the release is there now. Closing this as a duplicate of https://github.com/pypi/warehouse/issues/12214.

**Closed by di** 2022-09-26 15:53 UTC
Labels: requires triaging, bug :bug:
