### ISSUE TITLE
PyPI API doesn't return License if License is Specified as a Classifier

### ISSUE THREAD

**Issue by Paebbels** [pypi/warehouse#8960] opened 2021-01-04 09:17 UTC
**Describe the bug**
The service shields.io is used to render different equal looking badges for a big variety of services including PyPI. I discovered that license badges are differently displayed depending on how a license is specified in a Python package hosted on PyPI.

There are 2 variants to specify a license:
1. As parameter `license` to `setuptools.setup(...)`, or
2. As a classifier like `"License :: OSI Approved :: Apache Software License"`

Checking `setuptools` (also part of PyPA), the license parameter for `setuptools.setup()` is not documented in the user guide (see [setuptools "keywords"](https://setuptools.readthedocs.io/en/latest/userguide/keywords.html)), but in [full "keyword" list](https://setuptools.readthedocs.io/en/latest/references/keywords.html?highlight=license#keywords) and also not [recommended anymore](https://setuptools.readthedocs.io/en/latest/history.html?highlight=license#id232):
> v41.1.0 - Documentation changes: Use license classifiers rather than the license field.

It looks like the API of PyPI is broken and doesn't support the "new" style of specifying licenses. This causes problems in services using the PyPI API like shields.io.

**Expected behavior**
Independent of how a license is specified, the API should return a license name. At best this name is offered as SDPX identifier.

**To Reproduce**
See issue badges/shields#6013 on shields.io for reproduction and results.

> **From badges/shields#6013**
> When we grab the API response from PyPI (e.g: https://pypi.org/pypi/pyVHDLModel/json ) if the license key isn't populated, we just grab text from the classifier string so the reason the badge is `license | apache software` and not `license | apache 2.0` is because the classifier is `License :: OSI Approved :: Apache Software License` and not `License :: OSI Approved :: Apache 2.0 License`.

**My Platform**
The bug was discovered as a user of shields.io and when starting a discussion with shields.io developers what's going wrong.

**Additional context**

*None*

**Comment by di** [comment] 2021-01-05 17:44
The `License` and `Classifiers` fields are two separate metadata fields that have no effect on each other. E.g. at https://pypi.org/pypi/pip/json you will find both:

```json
...
"classifiers": [
"Development Status :: 5 - Production/Stable",
"Intended Audience :: Developers",
"License :: OSI Approved :: MIT License",
"Programming Language :: Python",
"Programming Language :: Python :: 2",
"Programming Language :: Python :: 2.7",
"Programming Language :: Python :: 3",
"Programming Language :: Python :: 3.5",
"Programming Language :: Python :: 3.6",
"Programming Language :: Python :: 3.7",
"Programming Language :: Python :: 3.8",
"Programming Language :: Python :: 3.9",
"Programming Language :: Python :: Implementation :: CPython",
"Programming Language :: Python :: Implementation :: PyPy",
"Topic :: Software Development :: Build Tools"
],
...
"license": "MIT",
...
```

This is not a bug in the API but a constraint of the metadata format, and there are edge cases which prevent this from changing (for example, what if multiple license classifiers are specified?).

There is some discussion to improve the metadata at https://discuss.python.org/t/pep-639-improving-license-clarity-with-better-package-metadata/2154. You may also be interested in https://github.com/pypa/trove-classifiers/issues/17.

**Comment by di** [comment] 2024-12-18 14:58
Closing: we have no plans to change this, and given that PEP 639 is now accepted, these classifiers are now deprecated and the `License-Expression` field should be used instead.

**Closed by di** 2024-12-18 14:58 UTC
Labels: feature request, blocked
