### ISSUE TITLE
Broken Documentation links on Gensim's PyPi page

### ISSUE THREAD

**Issue by computerscienceiscool** [pypi/warehouse#13937] opened 2023-06-14 06:03 UTC
# Broken links on Pypi gensim page #
This is the page with several broken links under the Documentation section: https://pypi.org/project/gensim/#documentation-1

Here is a link to the Issue posted on the gensim GitHub  [https://github.com/RaRe-Technologies/gensim/issues/3452](Link in gensim GitHub).  The links on their pages are correct and this is not a bug with the GenSim site, but broken links on the Pypi.org site.\

**Describe the bug**
Under the **Documentation** section of the page, all four links are broken

**Expected behavior**
I expect the links to take the reader to the correct location.  The gensim GitHub has many of the same resources listed on PyPi with working links.  This is under the documentation section of this page: https://github.com/RaRe-Technologies/gensim/blob/develop/README.md

**To Reproduce**
To reproduce this bug, go to https://pypi.org/project/gensim/#documentation-1 and click on the links in the Documentation section.  Each of the four links is broken.   

**My Platform**

 Windows 10, Firefox

**Additional context**
This is a link to the Issue listed on the gensim GitHub: https://github.com/RaRe-Technologies/gensim/issues/3452

**Comment by di** [comment] 2023-06-14 09:14
Duplicate of https://github.com/pypa/readme_renderer/issues/169.

**Closed by di** 2023-06-14 09:14 UTC
Labels: requires triaging, bug :bug:
