### ISSUE TITLE
Some projects exist only in the simple API.

### ISSUE THREAD

**Issue by domdfcoding** [pypi/warehouse#12207] opened 2022-09-12 10:50 UTC
**Describe the bug**
Some projects are listed at https://pypi.org/simple/, and have a page at `https://pypi.org/simple/<project>/`, but don't exist in the web UI or the JSON API (`https://pypi.org/project/<project>/` and `https://pypi.org/pypi/<project>/json`). 

Some names which exhibit this behaviour are `abcmodel`, `abstractdomain` and `access-control-python3-v1`.

Are these reserved/blocked names, perhaps because they were typosquats or malware?

**Expected behavior**
All projects listed at `/simple/` exist in the JSON API etc.

**To Reproduce**
* https://pypi.org/project/abcmodel/
* https://pypi.org/pypi/abcmodel/json

**My Platform**
N/A

**Additional context**

**Comment by di** [comment] 2022-09-12 12:58
This is expected. These are projects that exist and once had releases, but these releases were deleted by the maintainers. Because the JSON and project detail pages display individual releases, there's nothing to show for a project with no releases.

Essentially a duplicate of https://github.com/pypi/warehouse/issues/1388.

**Closed by di** 2022-09-12 12:58 UTC
Labels: requires triaging, bug :bug:
