### ISSUE TITLE
Mails are translated using the senders' language

### ISSUE THREAD

**Issue by almet** [pypi/warehouse#15094] opened 2023-12-20 20:41 UTC
**Describe the bug**

When receiving an email notification for a new publisher (a new publisher has been added to a project), the message is translated using the language of the sender (I guess using its User Agent language) rather than a language defined in my profile.

In my case, I received a message in half English / half Spanish, even though I'm speaking / reading french.

**Expected behavior**

I expected the messages to be translated using my language, and not the sender language.

(I also expect the translation to be complete, but I guess this is just because of missing translated strings).

**To Reproduce**

On a project, go with a browser configured in spanish and add a new publisher). Another user which has admin rights to the project will receive a mail in the first browser language.

**Comment by miketheman** [comment] 2023-12-20 20:43
Duplicate of #7583

**Closed by miketheman** 2023-12-20 20:43 UTC
Labels: requires triaging, bug :bug:

**Comment by di** [comment] 2023-12-20 20:55
I think this is not quite a duplicate of https://github.com/pypi/warehouse/issues/7583: we should be sending this email in the default locale (english) until https://github.com/pypi/warehouse/issues/7583 is resolved.
