### ISSUE TITLE
pypi says my project has no description but it does

### ISSUE THREAD

**Issue by helloDestroyerOfWorlds** [pypi/warehouse#13915] opened 2023-06-12 07:56 UTC
**Describe the bug**
 I think the title says it all.  It's the same as the title from a past closed issue, but I found it and I am still having the issue, so I want to re-open it essentially.

**Expected behavior**
 My pypi page to have a description.

**To Reproduce**

1.  Use twine to upload package using PyCharm's terminal and "py -m twine upload dist/*"
2.  I suppose there may be more to it than this, but this is all I have to do and it's repeatable for me.

**My Platform**
  Windows 10 using PyCharm IDE

**Additional context**
  

I realize the description is set by the "first upload" to pypi, so in all my troubleshooting I have always been clearing out my dist folder entirely before each attempt.  Two days ago my workflow worked flawlessly (using same "py -m twine upload dist/*") but then I was forced to start updating things, many, many things.  I used to use setup.cfg file, but now switched over to setup.py.  Never used to have a .pypirc file at all, now I have one, but still for some reason twine asks me for my credentials every single time, so I still just enter them.

I also had to add a PKG-INFO file that I never had, and moved most of the stuff that was in my setup.cfg file into this file, to maintain a minimal setup.py file as possible.  My setup.py file just has "setup(name='propdes', version='0.3.16', packages=find_packages())" in it.

2 days ago I was on version 0.2.X of propeller_design_tools, now I'm on version 0.3.16 of propdes, and I still cannot figure this out!!!  Help meeee!

**Comment by miketheman** [comment] 2023-06-12 12:40
Duplicate of #13916

**Closed by miketheman** 2023-06-12 12:40 UTC
Labels: requires triaging, bug :bug:

**Comment by TrojranHrorse** [comment] 2023-06-12 17:14
wait this isn't supposed to be closed.  please allow me to close it thank you.

**Comment by henryiii** [comment] 2023-06-12 17:24
See https://github.com/pypa/packaging-problems/issues/675 (and [TrojranHrorse](https://github.com/TrojranHrorse) was an account created 2 hours ago).

**Comment by helloDestroyerOfWorlds** [comment] 2023-06-12 17:30
I know it was.
