### ISSUE TITLE
Unable to join project for non-English language

### ISSUE THREAD

**Issue by icemac** [pypi/warehouse#12554] opened 2022-11-16 08:06 UTC
**Describe the bug**

I got an invitation to join the `zope.paste` project on PyPI.
Trying to accept it led to an HTTP-500 error.
I am using the German locale.

**Expected behavior**

After hitting the `accept` button I get added to the project. But I ran into a HTTP-500 error telling me PyPI could be down and I should look at the status page or the twitter account.

**To Reproduce**

* Get an invitation for a project.
* Set your language to `German` in the footer of the PyPI page. (This seems to be the critical part: after switching the language to English I was able to join.)
* Log-in to PyPI.
* Click the `accept` button -> get the HTTP-500 error.

**My Platform**

I do not think that my platform matters: I tried on Safari at iOS and macOS.
Having the locale set to German seems to be required to get the error.

**Comment by di** [comment] 2022-11-16 13:12
Duplicate of #12487 and #12552.

**Closed by di** 2022-11-16 13:12 UTC
Labels: requires triaging, bug :bug:
