### ISSUE TITLE
Allow API token to be scope to multiple projects

### ISSUE THREAD

**Issue by ashb** [pypi/warehouse#12176] opened 2022-09-05 12:30 UTC
Hello, I'm a member of the core team for Apache Airflow, and we have our project split up in to a number of distributions on PyPI - the core "apache-airflow" dist and (currently, but it grows over time) 70 provider modules, apache-airflow-providers-*.

I would like to be able to "easily" upload those provider dists via API tokens, but currently I either need to use an account-wide token, or each upload needs a separate API key (which doesn't easily work for our normal release workflow, where we will release all provider packages with changes once a month)

It's possible Organizations might help here if it's possible to have an Org-wide API token?

Relates to #7265

**Comment by dstufft** [comment] 2022-09-05 15:32
You can create an account wide token, then scope it yourself for multiple projects if that works for you, although I do agree ti would be nice for our UI to support multiple of them here.

**Comment by di** [comment] 2022-09-23 15:38
Hi, thanks for the issue. We agree this is a good idea, and that it's going to be much easier to implement to implement for organizations/teams once that feature has landed, so we'll consider this blocked on https://github.com/pypi/warehouse/issues/11590.

**Comment by Julian** [comment] 2023-03-17 15:55
Is this a duplicate of #6292 perhaps?

**Comment by di** [comment] 2023-03-17 16:25
Yep! Duplicate of #6292.

**Closed by di** 2023-03-17 16:25 UTC
Labels: feature request, blocked, organizations

**Comment by ttodua** [comment] 2025-04-03 10:14
> You can create an account wide token, then scope it yourself for multiple projects if that works for you, although I do agree ti would be nice for our UI to support multiple of them here.

Hi @dstufft , can you tell how to scope it to specific projects (after creating it for entire account scope)? can't find any way in UI.
